import {StyleSheet} from 'react-native';
import {getScaledDimension} from '../../utils/DynamicScaling';
export default StyleSheet.create({
  content: {
    backgroundColor: 'white',
    flex: 1,
  },
  header: {
    width: '100%',
    height: '8%',
   // backgroundColor: 'red',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: '4%',
    paddingRight: '4%',
  },
  headerImg: {},
  headerSearchImg: {
    marginLeft: 'auto',
  },
  headerTextParent: {
    marginTop:'1.2%',
   // backgroundColor: 'green',
    margin:0,
    padding:0
  },
  headerBig: {
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(16, 'font'),
    color: '#00214E',
  },
  headerSmall: {
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(10, 'font'),
    color: '#00214E',
  },
  hero: {
    marginTop: '4%',
    width: '92%',
    height: '5%',
    backgroundColor: 'red',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 8,
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    elevation: 3,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: '2%',
    paddingRight: '2%',
  },
  heroText: {
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(12, 'font'),
    color: '#00214E',
  },
  money: {
    marginLeft: 'auto',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: '#00214E',
    padding: '1%',
  },
  moneyText: {
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(12, 'font'),
    color: '#00214E',
  },
  bigText: {
    marginLeft: '4%',
    marginTop: '4%',
    fontFamily: 'Poppins-Medium',
    fontSize: getScaledDimension(24, 'font'),
    color: '#00214E',
  },
  nudge: {
    marginTop: '4%',
    width: '92%',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 20,
    // height: '15%',
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    elevation: 3,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '2%',
  },
  nudgeH1: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: getScaledDimension(24, 'font'),
    color: '#00214E',
  },
  nudgeDescription: {
    marginTop: '4%',
    width: '88%',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: '#BE4A4A',
    padding: '2%',
  },
  nudgeText: {
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(13, 'font'),
    color: '#00214E',
  },

  button: {
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '80%',
    //height: getScaledDimension(80, 'height'),
    backgroundColor: '#E9F2FF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: '4%',
    paddingBottom: '4%',
    marginTop: '8%',
    marginBottom: '2%',
  },
  buttonText: {
    fontFamily: 'Poppins-Medium',
    fontSize: getScaledDimension(18, 'font'),
    color: '#00214E',
  },
  mediumText: {
    marginLeft: '4%',
    marginTop: '4%',
    fontFamily: 'Poppins-Medium',
    fontSize: getScaledDimension(20, 'font'),
    color: '#00214E',
  },
  aaMenu: {
    // marginTop: '2%',
    width: '92%',
    height: '10%',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 5,
    // borderWidth: 0.5,
    borderColor: '#BE4A4A',
    // padding: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  aaMenuBox: {
    borderRadius: 8,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '4%',
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    elevation: 3,
    backgroundColor: 'white',
  },
  viewMore: {
    marginLeft: 'auto',
    fontFamily: 'Poppins-Medium',
    fontSize: getScaledDimension(15, 'font'),
    color: '#00214E',
  },
  rightArrow: {
    marginLeft: '10%',
  },
  bottomTab: {
    //  backgroundColor: 'red',
    marginTop: 'auto',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    height: '20%',

    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: -10},
    shadowRadius: 10,
    elevation: 3,
    //backgroundColor: 'white',
    alignItems: 'center',
  },
  pill: {
    backgroundColor: '#00214E',
    borderRadius: 20,
    height: 6,
    width: '30%',
    marginTop: '4%',
  },
  bottomTabText: {
    marginLeft: '4%',
    marginTop: '4%',
    marginRight: 'auto',
    fontFamily: 'Poppins-SemiBold',
    fontSize: getScaledDimension(20, 'font'),
    color: '#00214E',
  },
  hr: {
    backgroundColor: '#F4F4F4',
    borderWidth: 0.2,
    width: '92%',
    marginTop: '1%',
    borderRadius: 10,
  },
  menuParent: {
    //backgroundColor: 'green',
    width: '92%',
    height: '50%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  menuItems: {
    borderRadius: 8,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '4%',
    backgroundColor: 'white',
  },
  menuItemsText: {
    marginTop: '8%',
    fontFamily: 'Poppins-Regular',
    fontSize: getScaledDimension(10, 'font'),
    color: '#5C5C5C',
  },
  aaButtonPress:{
    flexDirection:'row',
    marginLeft:'auto'
  }
});
